import type { BotConfig, RepoRef, Logger } from '../types/index.js';
import {
  getDefaultBranch,
  getLatestCommit,
  createBranch,
  createCommit,
  createPullRequest,
  branchExists,
} from './github.js';
import { analyzeRepo } from './analyzer.js';
import { generateDocs, applyDocs } from './generator.js';

/**
 * Runs a full-repository documentation scan and opens a PR with the results.
 *
 * Called when the app is first installed on a repository (or when a repo is
 * added to an existing installation). Scans every code file, generates docs
 * for all undocumented public APIs, and opens a single PR.
 */
export async function bootstrapRepo(
  ref: RepoRef,
  config: BotConfig,
  log: Logger,
): Promise<{ prNumber: number } | null> {
  if (!config.bootstrap.enabled) {
    log.info('Bootstrap is disabled in config, skipping');
    return null;
  }

  const bootstrapBranch = config.bootstrap.branch;

  // Skip if a bootstrap PR branch already exists (avoid duplicate runs)
  if (await branchExists(ref, bootstrapBranch)) {
    log.info(
      `Branch ${bootstrapBranch} already exists — bootstrap PR was already created, skipping`,
    );
    return null;
  }

  const defaultBranch = await getDefaultBranch(ref);
  const head = await getLatestCommit(ref, defaultBranch);

  log.info(
    `Starting bootstrap scan of ${ref.owner}/${ref.repo} (${defaultBranch} @ ${head.sha.substring(0, 7)})`,
  );

  // --- Analyze ---
  const { gaps, fileContents } = await analyzeRepo(
    ref,
    defaultBranch,
    config,
    log,
  );

  if (gaps.length === 0) {
    log.info('No documentation gaps found — repo is fully documented');
    return null;
  }

  // --- Generate ---
  const generatedDocs = await generateDocs(gaps, fileContents, config);
  const fileUpdates = applyDocs(generatedDocs, fileContents);

  if (fileUpdates.length === 0) {
    log.info('LLM generation produced no file changes');
    return null;
  }

  // --- Create branch + commit ---
  await createBranch(ref, bootstrapBranch, head.sha);

  await createCommit(
    ref,
    bootstrapBranch,
    config.commit.message,
    fileUpdates,
    head.sha,
  );

  log.info(
    `Committed doc updates to ${bootstrapBranch} (${fileUpdates.length} files)`,
  );

  // --- Open PR ---
  const documented = generatedDocs.length;
  const remaining = gaps.length - documented;

  const body = buildBootstrapPRBody(
    gaps.length,
    documented,
    remaining,
    fileUpdates.length,
    fileUpdates.map((f) => f.path),
  );

  const prNumber = await createPullRequest(ref, {
    title: 'docs: add initial documentation for existing codebase',
    body,
    head: bootstrapBranch,
    base: defaultBranch,
  });

  log.info(`Opened bootstrap PR #${prNumber}`);

  return { prNumber };
}

function buildBootstrapPRBody(
  totalGaps: number,
  documented: number,
  remaining: number,
  filesUpdated: number,
  filePaths: string[],
): string {
  const lines: string[] = [
    '## Initial Documentation',
    '',
    'This PR was automatically generated by **github-docs-bot** when the app was',
    'installed on this repository. It adds documentation to public APIs that were',
    'missing doc comments.',
    '',
    '### Summary',
    '',
    '| Metric | Count |',
    '|--------|-------|',
    `| Undocumented elements found | ${totalGaps} |`,
    `| Auto-documented | ${documented} |`,
    `| Could not be documented | ${remaining} |`,
    `| Files updated | ${filesUpdated} |`,
    '',
  ];

  if (remaining > 0) {
    lines.push(
      '> Some elements could not be auto-documented. You may want to add',
      '> documentation for them manually.',
      '',
    );
  }

  lines.push('### Files changed', '');
  for (const path of filePaths.slice(0, 100)) {
    lines.push(`- \`${path}\``);
  }
  if (filePaths.length > 100) {
    lines.push(`- ... and ${filePaths.length - 100} more`);
  }

  lines.push(
    '',
    '---',
    '',
    '> Auto-generated by github-docs-bot. Future PRs in this repo will be',
    '> documented incrementally as files change.',
  );

  return lines.join('\n');
}
