import type { BotConfig, RepoRef, Logger } from '../types/index.js';
import {
  getDefaultBranch,
  getLatestCommit,
  createBranch,
  createCommit,
  createPullRequest,
  branchExists,
} from './github.js';
import { documentRepo } from './documenter.js';

const BOOTSTRAP_TIMEOUT_MS = 5 * 60 * 1000;

/**
 * Runs a full-repository documentation scan and opens a PR with the results.
 *
 * Called when the app is first installed on a repository (or when a repo is
 * added to an existing installation). Scans every code file, generates docs
 * for all undocumented public APIs, and opens a single PR.
 */
export async function bootstrapRepo(
  ref: RepoRef,
  config: BotConfig,
  log: Logger,
): Promise<{ prNumber: number } | null> {
  if (!config.bootstrap.enabled) {
    log.info('Bootstrap is disabled in config, skipping');
    return null;
  }

  const bootstrapBranch = config.bootstrap.branch;
  const branchAlreadyExists = await branchExists(ref, bootstrapBranch);

  if (branchAlreadyExists) {
    const existingPR = await findOpenPR(ref, bootstrapBranch);
    if (existingPR) {
      log.info(
        `Branch ${bootstrapBranch} already exists with open PR #${existingPR} — skipping`,
      );
      return null;
    }
    log.info(
      `Branch ${bootstrapBranch} exists but no open PR found — cleaning up and re-running`,
    );
  }

  const defaultBranch = await getDefaultBranch(ref);
  const head = await getLatestCommit(ref, defaultBranch);

  log.info(
    `Starting bootstrap scan of ${ref.owner}/${ref.repo} (${defaultBranch} @ ${head.sha.substring(0, 7)})`,
  );

  let result;
  try {
    result = await withTimeout(
      documentRepo(ref, defaultBranch, config, log),
      BOOTSTRAP_TIMEOUT_MS,
    );
  } catch (error) {
    if (error instanceof Error && error.message.includes('timed out')) {
      log.warn(
        { error },
        `Bootstrap timed out after ${BOOTSTRAP_TIMEOUT_MS / 1000}s for ${ref.owner}/${ref.repo}`,
      );
      return null;
    }
    throw error;
  }

  if (result.fileUpdates.length === 0) {
    log.info('No documentation changes needed — repo is fully documented');
    return null;
  }

  await createBranch(ref, bootstrapBranch, head.sha);

  try {
    await createCommit(
      ref,
      bootstrapBranch,
      config.commit.message,
      result.fileUpdates,
      head.sha,
    );

    log.info(
      `Committed doc updates to ${bootstrapBranch} (${result.fileUpdates.length} files)`,
    );

    const body = buildBootstrapPRBody(
      result.insertions.length,
      result.fileUpdates.length,
      result.filesAnalyzed,
      result.fileUpdates.map((f) => f.path),
    );

    const prNumber = await createPullRequest(ref, {
      title: 'docs: add initial documentation for existing codebase',
      body,
      head: bootstrapBranch,
      base: defaultBranch,
    });

    log.info(`Opened bootstrap PR #${prNumber}`);
    return { prNumber };
  } catch (error) {
    log.error(
      { error },
      `Bootstrap commit/PR failed for ${ref.owner}/${ref.repo} — branch ${bootstrapBranch} may need manual cleanup`,
    );
    throw error;
  }
}

async function findOpenPR(
  ref: RepoRef,
  head: string,
): Promise<number | null> {
  try {
    const { data: prs } = await ref.octokit.pulls.list({
      owner: ref.owner,
      repo: ref.repo,
      head: `${ref.owner}:${head}`,
      state: 'open',
      per_page: 1,
    });
    return prs.length > 0 ? prs[0].number : null;
  } catch {
    return null;
  }
}

async function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T> {
  let timer: ReturnType<typeof setTimeout>;
  const timeout = new Promise<never>((_, reject) => {
    timer = setTimeout(
      () => reject(new Error(`Bootstrap timed out after ${ms}ms`)),
      ms,
    );
  });
  try {
    return await Promise.race([promise, timeout]);
  } finally {
    clearTimeout(timer!);
  }
}

function buildBootstrapPRBody(
  docsAdded: number,
  filesUpdated: number,
  filesScanned: number,
  filePaths: string[],
): string {
  const lines: string[] = [
    '## Initial Documentation',
    '',
    'This PR was automatically generated by **github-docs-bot** when the app was',
    'installed on this repository. It adds documentation to public APIs that were',
    'missing doc comments.',
    '',
    '### Summary',
    '',
    '| Metric | Count |',
    '|--------|-------|',
    `| Files scanned | ${filesScanned} |`,
    `| Doc comments added | ${docsAdded} |`,
    `| Files updated | ${filesUpdated} |`,
    '',
    '### Files changed',
    '',
  ];

  for (const path of filePaths.slice(0, 100)) {
    lines.push(`- \`${path}\``);
  }
  if (filePaths.length > 100) {
    lines.push(`- ... and ${filePaths.length - 100} more`);
  }

  lines.push(
    '',
    '---',
    '',
    '> Auto-generated by github-docs-bot. Future PRs in this repo will be',
    '> documented incrementally as files change.',
  );

  return lines.join('\n');
}
