import type { Context } from 'probot';
import { loadConfig } from '../config/loader.js';
import { documentPR } from '../services/documenter.js';
import { commitDocUpdates } from '../services/committer.js';
import { notifyPortalRevalidation } from '../services/revalidate.js';
import { withLock } from '../services/lock.js';
import { isDuplicate } from '../services/dedup.js';
import { increment } from '../services/metrics.js';
import type { BotConfig, RepoRef } from '../types/index.js';

const BOT_SUFFIX = '[bot]';

function shouldSkip(
  context: Context<'pull_request'>,
  config: BotConfig,
): boolean {
  const pr = context.payload.pull_request;
  const sender = context.payload.sender.login;
  const action = context.payload.action;

  if (sender.endsWith(BOT_SUFFIX)) return true;
  if (config.triggers.skip_draft && pr.draft) return true;

  if (
    config.triggers.only_on_ready_for_review &&
    action !== 'ready_for_review'
  ) {
    return true;
  }

  const labels = pr.labels.map((l) => l.name);
  if (config.triggers.skip_labels.some((skip) => labels.includes(skip)))
    return true;

  return false;
}

export async function handlePullRequest(
  context: Context<'pull_request'>,
): Promise<void> {
  if (isDuplicate(context.id)) {
    increment('webhooksDeduplicated');
    context.log.info(`Skipping duplicate delivery ${context.id}`);
    return;
  }

  const pr = context.payload.pull_request;
  const { owner, repo } = context.repo();
  const lockKey = `${owner}/${repo}#${pr.number}`;

  return withLock(lockKey, () => processPullRequest(context));
}

async function processPullRequest(
  context: Context<'pull_request'>,
): Promise<void> {
  const pr = context.payload.pull_request;
  const { owner, repo } = context.repo();
  const ref: RepoRef = { octokit: context.octokit, owner, repo };
  const log = context.log;

  increment('webhooksReceived');
  log.info(`Processing PR #${pr.number}: ${pr.title}`);

  const config = await loadConfig(ref, pr.base.ref);

  if (shouldSkip(context, config)) {
    increment('webhooksSkipped');
    log.info('Skipping PR based on config/filters');
    return;
  }

  increment('prsProcessed');

  let checkRunId: number | undefined;

  try {
    const inProgressCheck = await context.octokit.checks.create({
      owner,
      repo,
      name: 'Documentation Coverage',
      head_sha: pr.head.sha,
      status: 'in_progress',
      output: {
        title: 'Analyzing documentation coverage...',
        summary: 'Scanning changed files for missing documentation.',
      },
    });
    checkRunId = inProgressCheck.data.id;

    const result = await documentPR(ref, pr.number, pr.head.ref, config, log);

    if (result.insertions.length === 0) {
      await context.octokit.checks.update({
        owner,
        repo,
        check_run_id: checkRunId,
        status: 'completed',
        conclusion: 'success',
        output: {
          title: 'All public APIs are documented',
          summary: `Scanned ${result.filesAnalyzed} files — no documentation gaps found.`,
        },
      });
      return;
    }

    if (result.fileUpdates.length > 0) {
      await commitDocUpdates(
        ref,
        pr.head.ref,
        config,
        result.fileUpdates,
        log,
      );
    }

    const documented = result.insertions.length;
    const filesUpdated = result.fileUpdates.length;

    const summary = [
      '| Metric | Count |',
      '|--------|-------|',
      `| Files scanned | ${result.filesAnalyzed} |`,
      `| Doc comments added | ${documented} |`,
      `| Files updated | ${filesUpdated} |`,
    ].join('\n');

    await context.octokit.checks.update({
      owner,
      repo,
      check_run_id: checkRunId,
      status: 'completed',
      conclusion: 'success',
      output: {
        title: `Documented ${documented} element${documented === 1 ? '' : 's'} across ${filesUpdated} file${filesUpdated === 1 ? '' : 's'}`,
        summary,
      },
    });

    increment('prsDocumented');
    increment('docsGenerated', documented);
    increment('filesAnalyzed', result.filesAnalyzed);

    if (filesUpdated > 0) {
      try {
        await context.octokit.issues.createComment({
          owner,
          repo,
          issue_number: pr.number,
          body: `## Documentation Updated\n\n${summary}\n\n> Auto-generated by github-docs-bot`,
        });
      } catch (commentError) {
        log.warn({ error: commentError }, 'Failed to post PR comment');
      }
      await notifyPortalRevalidation(`${owner}/${repo}`, log);
    }
  } catch (error) {
    increment('prsFailed');
    log.error({ error }, 'Failed to process PR');

    if (checkRunId) {
      try {
        await context.octokit.checks.update({
          owner,
          repo,
          check_run_id: checkRunId,
          status: 'completed',
          conclusion: 'failure',
          output: {
            title: 'Documentation analysis failed',
            summary: `An error occurred: ${error instanceof Error ? error.message : 'Unknown error'}`,
          },
        });
      } catch (checkError) {
        log.error({ error: checkError }, 'Failed to update check run');
      }
    }
  }
}
