import type { Context } from 'probot';
import { loadConfig } from '../config/loader.js';
import { analyzePR } from '../services/analyzer.js';
import { generateDocs, applyDocs } from '../services/generator.js';
import { commitDocUpdates } from '../services/committer.js';
import type { BotConfig, RepoRef } from '../types/index.js';

const BOT_SUFFIX = '[bot]';

function shouldSkip(
  context: Context<'pull_request'>,
  config: BotConfig,
): boolean {
  const pr = context.payload.pull_request;
  const sender = context.payload.sender.login;

  if (sender.endsWith(BOT_SUFFIX)) return true;
  if (config.triggers.skip_draft && pr.draft) return true;

  const labels = pr.labels.map((l) => l.name);
  if (config.triggers.skip_labels.some((skip) => labels.includes(skip)))
    return true;

  return false;
}

export async function handlePullRequest(
  context: Context<'pull_request'>,
): Promise<void> {
  const pr = context.payload.pull_request;
  const { owner, repo } = context.repo();
  const ref: RepoRef = { octokit: context.octokit, owner, repo };
  const log = context.log;

  log.info(`Processing PR #${pr.number}: ${pr.title}`);

  const config = await loadConfig(ref, pr.base.ref);

  if (shouldSkip(context, config)) {
    log.info('Skipping PR based on config/filters');
    return;
  }

  const inProgressCheck = await context.octokit.checks.create({
    owner,
    repo,
    name: 'Documentation Coverage',
    head_sha: pr.head.sha,
    status: 'in_progress',
    output: {
      title: 'Analyzing documentation coverage...',
      summary: 'Scanning changed files for missing documentation.',
    },
  });

  try {
    const { gaps, fileContents } = await analyzePR(
      ref,
      pr.number,
      pr.head.ref,
      config,
      log,
    );

    if (gaps.length === 0) {
      await context.octokit.checks.update({
        owner,
        repo,
        check_run_id: inProgressCheck.data.id,
        status: 'completed',
        conclusion: 'success',
        output: {
          title: 'All public APIs are documented',
          summary: 'No documentation gaps found in changed files.',
        },
      });
      return;
    }

    const generatedDocs = await generateDocs(gaps, fileContents, config);
    const fileUpdates = applyDocs(generatedDocs, fileContents);

    let headSha = pr.head.sha;
    if (fileUpdates.length > 0) {
      const commitSha = await commitDocUpdates(
        ref,
        pr.head.ref,
        config,
        fileUpdates,
        log,
      );
      if (commitSha) headSha = commitSha;
    }

    const documented = new Set(
      generatedDocs.map((d) => `${d.gap.file}:${d.gap.name}`),
    );
    const remainingGaps = gaps.filter(
      (g) => !documented.has(`${g.file}:${g.name}`),
    );

    const conclusion =
      remainingGaps.length === 0
        ? 'success'
        : config.check.conclusion_on_missing;

    const annotations = remainingGaps.map((gap) => ({
      path: gap.file,
      start_line: gap.startLine,
      end_line: gap.startLine,
      annotation_level: 'warning' as const,
      message: `Missing documentation for ${gap.kind} \`${gap.name}\``,
    }));

    const summary = buildSummary(
      gaps.length,
      generatedDocs.length,
      remainingGaps.length,
      fileUpdates.length,
    );

    await context.octokit.checks.update({
      owner,
      repo,
      check_run_id: inProgressCheck.data.id,
      status: 'completed',
      conclusion,
      output: {
        title:
          remainingGaps.length === 0
            ? `Documented ${generatedDocs.length} element${generatedDocs.length === 1 ? '' : 's'}`
            : `${remainingGaps.length} element${remainingGaps.length === 1 ? '' : 's'} still need documentation`,
        summary,
        annotations: annotations.slice(0, 50),
      },
    });

    if (fileUpdates.length > 0) {
      await context.octokit.issues.createComment({
        owner,
        repo,
        issue_number: pr.number,
        body: `## Documentation Updated\n\n${summary}\n\n> Auto-generated by github-docs-bot`,
      });
    }
  } catch (error) {
    log.error({ error }, 'Failed to process PR');

    await context.octokit.checks.update({
      owner,
      repo,
      check_run_id: inProgressCheck.data.id,
      status: 'completed',
      conclusion: 'failure',
      output: {
        title: 'Documentation analysis failed',
        summary: `An error occurred: ${error instanceof Error ? error.message : 'Unknown error'}`,
      },
    });
  }
}

function buildSummary(
  totalGaps: number,
  documented: number,
  remaining: number,
  filesUpdated: number,
): string {
  const lines: string[] = [
    '| Metric | Count |',
    '|--------|-------|',
    `| Documentation gaps found | ${totalGaps} |`,
    `| Auto-documented | ${documented} |`,
    `| Still missing | ${remaining} |`,
    `| Files updated | ${filesUpdated} |`,
  ];

  if (remaining > 0) {
    lines.push(
      '',
      '> Some elements could not be auto-documented. See the check annotations for details.',
    );
  }

  return lines.join('\n');
}
