import type { Context } from 'probot';
import { loadConfig } from '../config/loader.js';
import { documentPR } from '../services/documenter.js';
import { commitDocUpdates } from '../services/committer.js';
import type { BotConfig, RepoRef } from '../types/index.js';

const BOT_SUFFIX = '[bot]';

function shouldSkip(
  context: Context<'pull_request'>,
  config: BotConfig,
): boolean {
  const pr = context.payload.pull_request;
  const sender = context.payload.sender.login;

  if (sender.endsWith(BOT_SUFFIX)) return true;
  if (config.triggers.skip_draft && pr.draft) return true;

  const labels = pr.labels.map((l) => l.name);
  if (config.triggers.skip_labels.some((skip) => labels.includes(skip)))
    return true;

  return false;
}

export async function handlePullRequest(
  context: Context<'pull_request'>,
): Promise<void> {
  const pr = context.payload.pull_request;
  const { owner, repo } = context.repo();
  const ref: RepoRef = { octokit: context.octokit, owner, repo };
  const log = context.log;

  log.info(`Processing PR #${pr.number}: ${pr.title}`);

  const config = await loadConfig(ref, pr.base.ref);

  if (shouldSkip(context, config)) {
    log.info('Skipping PR based on config/filters');
    return;
  }

  const inProgressCheck = await context.octokit.checks.create({
    owner,
    repo,
    name: 'Documentation Coverage',
    head_sha: pr.head.sha,
    status: 'in_progress',
    output: {
      title: 'Analyzing documentation coverage...',
      summary: 'Scanning changed files for missing documentation.',
    },
  });

  try {
    const result = await documentPR(ref, pr.number, pr.head.ref, config, log);

    if (result.insertions.length === 0) {
      await context.octokit.checks.update({
        owner,
        repo,
        check_run_id: inProgressCheck.data.id,
        status: 'completed',
        conclusion: 'success',
        output: {
          title: 'All public APIs are documented',
          summary: `Scanned ${result.filesAnalyzed} files — no documentation gaps found.`,
        },
      });
      return;
    }

    let headSha = pr.head.sha;
    if (result.fileUpdates.length > 0) {
      const commitSha = await commitDocUpdates(
        ref,
        pr.head.ref,
        config,
        result.fileUpdates,
        log,
      );
      if (commitSha) headSha = commitSha;
    }

    const documented = result.insertions.length;
    const filesUpdated = result.fileUpdates.length;

    const summary = [
      '| Metric | Count |',
      '|--------|-------|',
      `| Files scanned | ${result.filesAnalyzed} |`,
      `| Doc comments added | ${documented} |`,
      `| Files updated | ${filesUpdated} |`,
    ].join('\n');

    await context.octokit.checks.update({
      owner,
      repo,
      check_run_id: inProgressCheck.data.id,
      status: 'completed',
      conclusion: 'success',
      output: {
        title: `Documented ${documented} element${documented === 1 ? '' : 's'} across ${filesUpdated} file${filesUpdated === 1 ? '' : 's'}`,
        summary,
      },
    });

    if (filesUpdated > 0) {
      await context.octokit.issues.createComment({
        owner,
        repo,
        issue_number: pr.number,
        body: `## Documentation Updated\n\n${summary}\n\n> Auto-generated by github-docs-bot`,
      });
    }
  } catch (error) {
    log.error({ error }, 'Failed to process PR');

    await context.octokit.checks.update({
      owner,
      repo,
      check_run_id: inProgressCheck.data.id,
      status: 'completed',
      conclusion: 'failure',
      output: {
        title: 'Documentation analysis failed',
        summary: `An error occurred: ${error instanceof Error ? error.message : 'Unknown error'}`,
      },
    });
  }
}
